[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=📲 国内IP锁定,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/115login
ruleset=📲 谷歌FCM推送,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/Google-Play-Store(DIY)
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/Google-additional-Callis
ruleset=🌍 国外媒体(通用),https://raw.githubusercontent.com/carrollis/ios_rule_script-Callis/refs/heads/master/rule/Clash/LinkedIn/LinkedIn.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/carrollis/dead-horse/refs/heads/master/anti-ad-white-for-clash(Teddy).yaml
ruleset=🎯 全球直连,https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/refs/heads/master/anti-ad-white-for-clash.yaml
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/Callis-DIY-Domestic
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/TeamViewer.list
ruleset=🔮 流媒体登录,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/Callis-DIY-GlobalMediaLogin
ruleset=🌍 国外媒体(锁区),https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/Callis-DIY-IPTV(Global-Specific)
ruleset=🌍 国外媒体(通用),https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/Callis-DIY-IPTV(Global-General)
ruleset=🌍 国外媒体(通用),https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/Callis-DIY-MediaCDN(Global)
ruleset=📺 BBC,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/0dc7ef56cf2f082ad2af2dbe686af224c58d7fd4/rule/Clash/BBC/BBC.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/Apple-additional-Callis.list
ruleset=🔮 Github,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🐹 Disney+,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/Disney%2B(Additional-DIY).list
ruleset=🐹 Disney+,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=🎦 HBO,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/refs/heads/master/Clash/Ruleset/HBO(Additional)
ruleset=🎦 HBO,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=📺 DAZN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DAZN.list
ruleset=🍎 苹果TV,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
ruleset=📲 亚马逊,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Amazon.list
ruleset=📲 亚马逊,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=🎶 AbemaTV,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AbemaTV.list
ruleset=📺 Tiktok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🔮 海外AI服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🔮 Discord,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.list
ruleset=🎶 AbemaTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Abema/Abema.list
ruleset=🎶 AbemaTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AbemaTV/AbemaTV.list
ruleset=🎮 国外下载,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/GameDownload-Callis.list
ruleset=🎮 国外下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list
ruleset=🎮 国内下载,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 PS平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Battle/Battle.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 PC平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎮 任天堂平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎮 Xbox平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.list
ruleset=🎮 海外手游,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/DIY-Game
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/NetflixIP.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/carrollis/ACL4SSR-Carrollis/master/Clash/Ruleset/NetflixIP-add.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体(通用),https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 其他备用`[]🔮 私人固定`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🛩️ 美国备用`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🛩️ 日本备用`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🛩️ 英国备用`select`(英|英国|不列颠|大不列颠|日不落|UK|EN)
custom_proxy_group=🛩️ 香港备用`select`(港|HK|Hong Kong)
custom_proxy_group=🛩️ 台湾备用`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🛩️ 新加坡备用`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🛩️ IP海外固定`select`.*
custom_proxy_group=🛩️ IP国内固定`select`.*
custom_proxy_group=🛩️ 其他备用`select`.*
custom_proxy_group=🔮 私人固定`select`(私人|Teddy)
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 谷歌FCM推送`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点
custom_proxy_group=📢 谷歌服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 其他备用`[]🔮 私人固定
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🔮 流媒体登录`select`[]🔮 私人固定`[]🏖️ 私人智选`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🐹 Disney+`select`[]🚀 节点选择`[]♻️ 自动选择`[]🛩️ IP国内固定`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🎦 HBO`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🎵 Spotify`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🎶 AbemaTV`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📺 DAZN`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📺 BBC`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🇬🇧 英国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🍎 苹果TV`select`[]🚀 节点选择`[]♻️ 自动选择`[]🛩️ IP国内固定`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📲 亚马逊`select`[]🚀 节点选择`[]♻️ 自动选择`[]🛩️ IP国内固定`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📺 Tiktok`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🛩️ IP国内固定`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇨🇳 台湾节点`[]🇭🇰 香港节点
custom_proxy_group=🌍 国外媒体(通用)`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🛩️ 其他备用`[]🔮 私人固定`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌍 国外媒体(锁区)`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🛩️ 其他备用`[]🔮 私人固定`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🔮 Github`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🔮 海外AI服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🔮 Discord`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 国外下载`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 国内下载`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 PC平台`select`[]DIRECT`[]🛩️ 其他备用`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 PS平台`select`[]DIRECT`[]🛩️ 其他备用`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 Xbox平台`select`[]DIRECT`[]🛩️ 其他备用`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 任天堂平台`select`[]DIRECT`[]🛩️ 其他备用`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎮 海外手游`select`[]DIRECT`[]🛩️ 其他备用`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🛩️ 美国备用`[]🛩️ 日本备用`[]🛩️ 新加坡备用`[]🛩️ 香港备用`[]🛩️ 台湾备用`[]🛩️ 英国备用`[]🛩️ 其他备用
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=📲 海外IP锁定`select`[]🛩️ IP海外固定`[]🛩️ IP国内固定`[]🚀 节点选择`[]🔮 私人固定`[]DIRECT
custom_proxy_group=📲 国内IP锁定`select`[]🛩️ IP海外固定`[]🛩️ IP国内固定`[]🚀 节点选择`[]🔮 私人固定`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🏖️ 私人智选`url-test`(私人|Teddy)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(英|英国|不列颠|大不列颠|日不落|UK|EN)`http://www.gstatic.com/generate_204`300,,50


;设置分组标志位
